<!DOCTYPE html>
<html>
	<head>
		<title>Branch Input</title>
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
		<link rel="shortcut icon" href="<?php echo $baseUrl; ?>/resources/img/mycurrency.png" type="img/png">
		<meta name='description' content='မြန်နိုင်ငံ ရှိ သက်ဆိုင်ရာ ဘဏ်များ၏ ဘဏ်ခွဲများ နှင့် ပတ်သက်ပြီး Information ဖြည့်စွက်ပေးရန်ဖြစ်ပါသည်။'>
		<meta name='title' content='ဘဏ်ခွဲ | $ Exchange Rate'>
		<meta name='og:title' content='ဘဏ်ခွဲ | $ Exchange Rate'/>
		<meta property='og:image' content='https://kyawhtut.com/public/img/mmexchange-screen-shoot.png' />
		<meta property='og:description' content='မြန်နိုင်ငံ ရှိ သက်ဆိုင်ရာ ဘဏ်များ၏ ဘဏ်ခွဲများ နှင့် ပတ်သက်ပြီး Information ဖြည့်စွက်ပေးရန်ဖြစ်ပါသည်။' />
		<meta name='og:author' content='Kyaw Htut'/>
		<meta name='og:image:alt' content='Kyaw Htut'/>
		<meta property='og:url' content='https://kyawhtut.com/mmexchange/' />
		<meta name='author' content='Kyaw Htut'>
		<meta name="theme-color" content="#719e40">
		<link rel="stylesheet" href="<?php echo $baseUrl; ?>/resources/css/4.3.1/bootstrap.min.css">
		<link rel="stylesheet" href="<?php echo $baseUrl; ?>/resources/css/bootstrap-select.min.css">
		<link rel="stylesheet" href="<?php echo $baseUrl; ?>/resources/css/photo-upload.min.css">
		<link rel="stylesheet" href="<?php echo $baseUrl; ?>/resources/css/style.css">
		<link rel="stylesheet" href="<?php echo $baseUrl; ?>/resources/css/font-awesome.css">
		<style>
		</style>
	</head>
	<body>
		<nav class="navbar navbar-expand-lg fixed-top navbar-light bg-light">
			<a class="navbar-brand" href="<?= $baseUrl; ?>/branch-input">My Currency</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarTogglerDemo02">
				<div class="navbar-nav mr-auto mt-2 mt-lg-0"></div>
				<ul class="navbar-nav my-2 my-lg-0" style="float: left;">
					<li class="nav-item"><a href="http://bit.ly/kh-mycurrency">Apk Download</a></li>
				</ul>
			</div>
		</nav>
		<div class="container" style="margin-top: 72px;">
			<div>
				<h2 class="text-left subTitle">ဘဏ်ခွဲ အချက်အလက်</h2>
			</div>
			<br>
			<div class="alert alert-success alert-dismissible fade show" role="alert"></div>
			<form method="post" id="saveForm" >
				<div style="display: none;" class="form-group row">
					<label style="float : left; text-align: start; padding-right: 0;" class="col-sm-2 col-form-label" for="id">branchId</label>
					<div class="col-sm-10">
						<input class="form-control" type="text" id="id" name="id" placeholder="branchId" value="<?= $branchId; ?>" maxlength="255">
					</div>
				</div>
				<div class="form-group row">
					<label style="float : left; text-align: start; padding-right: 0;" class="col-sm-2 col-form-label" for="bank_type">အမျိုးအစား</label>
					<div class="col-sm-10"> 
						<select class="selectpicker form-control" id="bank_type" name="bank_type" data-live-search="true">
						</select>
					</div>
				</div>
				<div class="form-group row">
					<label style="float : left; text-align: start; padding-right: 0;" class="col-sm-2 col-form-label" for="bankDropDown">ဘဏ်</label>
					<div class="col-sm-10"> 
						<select class="selectpicker form-control" id="bankDropDown" name="bank_id" data-live-search="true">
							<option>ဧရာဝတီဘဏ်</option>
						</select>
					</div>
				</div>
				<div class="form-group row">
					<label style="float : left; text-align: start; padding-right: 0;" class="col-sm-2 col-form-label" for="bank_branch_name">အမည်</label>
					<div class="col-sm-10">
						<input class="form-control" type="text" id="bank_branch_name" name="bank_branch_name" placeholder="အမည်" value="<?= $bank_branch_name; ?>" maxlength="255" required autofocus>
					</div>
				</div>
				<div class="form-group row" id="divBankPhone">
					<label style="float : left; text-align: start; padding-right: 0;" class="col-sm-2 col-form-label" for="bank_branch_ph_no">ဖုန်းနံပါတ်</label>
					<div class="col-sm-10">
						<input class="form-control" type="text" id="bank_branch_ph_no" name="bank_branch_ph_no" placeholder="ဖုန်းနံပါတ်" value="<?= $bank_branch_ph_no; ?>" maxlength="255" autofocus>
					</div>
				</div>
				<div class="form-group row">
					<label style="float : left; text-align: start; padding-right: 0;" class="col-sm-2 col-form-label" for="cityDropDown">တိုင်းဒေသကြီး</label>
					<div class="col-sm-10"> 
						<select class="selectpicker form-control" id="cityDropDown" name="city_id" data-live-search="true">
							<option>ရန်ကုန်</option>
						</select>
					</div>
				</div>
				<div class="form-group row">
					<label style="float : left; text-align: start; padding-right: 0;" class="col-sm-2 col-form-label" for="townshipDropDown">မြို့နယ်</label>
					<div class="col-sm-10"> 
						<select class="selectpicker form-control" id="townshipDropDown" name="township_id" data-live-search="true">
							<option>ကြည့်မြင်တိုင်</option>
						</select>
					</div>
				</div>
				<div class="form-group row">
					<label style="float: left; text-align: start; padding-right: 0;" class="col-sm-2 col-form-label" for="photo">ဓာတ်ပုံ</label>
					<div class="col-sm-10">
						<!-- Photo upload -->
						<div class="form-image-list form-control" style="border: none; background-color: white; box-shadow: none; padding-left: 0;">
							<div class="form-image" style="float: left;">
								<input type="hidden" id="basename" value="7AE70550-9CF2-11E9-A11C-E59E45735C94">
								<span id="image-add-continer" class="image-add-continer">
									<a class="image-add" data-toggle="modal" data-target="#dialogUploadImage">
										<i class="fa fa-plus"></i>
									</a>
								</span>
								<span id="image-preview-container" class="image-preview-container">
									<input id="bankPhoto" name="bank_branch_image" type="hidden" value="<?= $bank_branch_image; ?>">
									<img id="image-preview" class="form-image-preview">
									<div class="image-delete-container">
										<a class="image-delete" title="Remove">
											<i class="fa fa-trash-o"></i>
										</a>
									</div>
								</span>
							</div>
						</div>
					</div>
				</div>
				<div class="form-group row">
					<label style="float : left; text-align: start; padding-right: 0;" class="col-sm-2 col-form-label" for="description">အကြောင်းအရာ</label>
					<div class="col-sm-10"> 
						<textarea placeholder="အကြောင်းအရာ" class="form-control" id="description" name="bank_description" maxlength="225" required style="resize: vertical;"><?= $bank_description; ?></textarea>
					</div>
				</div>
				<div class="form-group row" style="margin-bottom: 0rem;">
					<label style="float : left; text-align: start; padding-right: 0;" class="col-sm-2 col-form-label" for="latitude">တည်နေရာ</label>
					<div class="col-sm-10 row" style="padding-right: 0;"> 
						<dir class="col-sm-6" style="margin-top: 0; padding-right: 0;">
							<input class="form-control" type="number" step="any" id="latitude" name="bank_lat" placeholder="Latitude" value maxlength="255" required autofocus>
						</dir>
						<dir class="col-sm-6" style="margin-top: 0; padding-right: 0;">
							<input class="form-control" type="number" step="any" id="longitude" name="bank_long" placeholder="Longitude" value maxlength="255" required autofocus>
						</dir>
					</div>
				</div>
				<div class="form-group row">
					<div class='col-sm-12 row' style="margin-left: 1px;">
						<div id="map" class='map' style="width: 100%; height: 400px;"></div>
					</div>
				</div>
				<div class="form-group row form-actions text-center">
					<div class="col-sm-12 ">
						<button class="btn btn-primary" type="submit" role="button">Save</button>
						<a class="btn btn-outline-secondary" href="<?= $baseUrl; ?>/branch-input" role="button" id="actionCancel">Cancel</a>
					</div>
				</div>
			</form>
			<div class="footer">
				<div class="col-md-12 text-center">
					<p>Developed by © <a href="https://kyawhtut.com/" target="_blank">Kyaw Htut</a></p>
				</div>
			</div>
		</div>
		<!-- Photo upload dialog modal -->
		<div class="modal fade bd-example-modal" tabindex="-1" role="dialog" id="dialogUploadImage">
			<div class="modal-dialog" role="document">
				<div class="modal-content">
					<div class="modal-body">
						<div class="modal-container model-upload text-center">
							<i class="fa fa-cloud-upload"></i>
							<h4 class="h4">Image Uploader</h4>
							<div class="progress">
								<div class="progress-bar" role="progressbar"></div>
							</div><br>
							<button id="upload-btn" class="btn btn-lg btn-primary" type="button">Select Image</button>
							<input id="upload-input" class="upload-input" type="file" name="uploads[]" accept="image/jpeg,image/x-png" />
						</div>
					</div>
					<div class="modal-footer">
						<button class='btn btn-outline-secondary' id='dialogUploadImageCancel' type='button' data-dismiss='modal'>Close</button>
					</div>
				</div>
			</div>
		</div>
		<form action="<?= $baseUrl; ?>/branch-input" method="get" id="backFrm"></form>
		<script>
			function initMap() {
				var latlng = {
					lat: <?= $bankLat; ?>,
					lng: <?= $bankLong; ?>
				};
				$('#latitude').val(latlng.lat);
				$('#longitude').val(latlng.lng);
				var map = new google.maps.Map(document.getElementById('map'), {
					zoom: 15,
					center: latlng
				});
				var marker = new google.maps.Marker({
					position: latlng,
					map: map
				});
				google.maps.event.addListener(map, 'click', function(event) {
					if (marker) marker.setMap(null);
					marker = new google.maps.Marker({
						position: event.latLng,
						map: map
					});
					$('#latitude').val(event.latLng.lat());
					$('#longitude').val(event.latLng.lng());
				});
				if ("geolocation" in navigator) {
					navigator.geolocation.getCurrentPosition(function(position){
						<?php if($branchId == 0) { ?>
							var pos = {
								lat: position.coords.latitude, 
								lng: position.coords.longitude
							};
							// infoWindow = new google.maps.InfoWindow({map: map});
							// infoWindow.setPosition(pos);
							// infoWindow.setContent(
							// 	"Found your location <br />Lat : "+position.coords.latitude+" </br>Lang :"+ position.coords.longitude);
							map.panTo(pos);
							if (marker) marker.setMap(null);
							marker = new google.maps.Marker({
								position: pos,
								map: map
							});
							$('#latitude').val(position.coords.latitude);
							$('#longitude').val(position.coords.longitude);
						<?php } ?>
						console.log("Get location");
					});
				}else{
					console.log("Geolocation not available!");
				}
			}
	    </script>
		<script src="<?php echo $baseUrl; ?>/resources/js/jquery.js"></script>
		<script src="<?php echo $baseUrl; ?>/resources/js/popper.min.js"></script>
		<script src="<?php echo $baseUrl; ?>/resources/js/4.3.1/bootstrap.min.js"></script>
		<script src="<?php echo $baseUrl; ?>/resources/js/bootstrap-select.min.js"></script>
		<script src="<?php echo $baseUrl; ?>/resources/js/photo-upload.min.js"></script>
		<script src="<?php echo $baseUrl; ?>/resources/js/script-upload.js"></script>
		<!-- map api -->
		<script type="text/javascript">
			initImageUpload('<?= $baseUrl; ?>',"#bankPhoto","");
			$(document).ready(function() {

				$('.alert').hide();

				$('.close').on('click', function(e) {
					$('.alert').hide();
				})

				setBankType();

				$.get("<?php echo $baseUrl; ?>/api/v2/bank_table", function(data) {
					$("#bankDropDown").empty();
					$("#bankDropDown").append("<option disabled>Choose Bank</option>");
					for (var index in data.bank_table) {
						if(data.bank_table[index].id == <?= $bankId; ?>) {
							$("#bankDropDown").append("<option selected value='" + data.bank_table[index].id + "'>" + data.bank_table[index].bank_name + "</option>");
						} else {
							$("#bankDropDown").append("<option value='" + data.bank_table[index].id + "'>" + data.bank_table[index].bank_name + "</option>");
						}
					}
					$("#bankDropDown").selectpicker('refresh');
				})

				$.get("<?php echo $baseUrl; ?>/api/v2/city", function(data) {
					$('#cityDropDown').empty();
					var cityList = data.city;
					for(var index in cityList) {
						if(cityList[index].id == <?= $cityId; ?>) {
							$("#cityDropDown").append("<option selected value='" + cityList[index].id + "'>" + cityList[index].city + "</option>");
						} else {
							$("#cityDropDown").append("<option value='" + cityList[index].id + "'>" + cityList[index].city + "</option>");
						}
					}
					$('#cityDropDown').selectpicker('refresh');
					townshipDataChange($('#cityDropDown').val());
				})

				$('#cityDropDown').change(function() {
					townshipDataChange(this.value);
				})
				$('#bank_type').change(function() {
					var value = "block";
					if(this.value + "" == "atm") {
						value = "none";
					}
					console.log(value);
					$('#divBankPhone').css({
						'display' : value
					});
				})

				$('#saveForm').submit(function(event) {
					var formData = {
						'id' : $('input[name=id]').val(),
						"bank_type": $("#bank_type").val(),
						"bank_id": $("#bankDropDown").val(),
						"bank_branch_name": $('input[name=bank_branch_name]').val(),
						"bank_branch_ph_no": $('input[name=bank_branch_ph_no]').val(),
						"city_id": $("#cityDropDown").val(),
						"township_id": $("#townshipDropDown").val(),
						"bank_branch_image": $('input[name=bank_branch_image]').val(),
						"bank_description": $('textarea[name=bank_description]').val(),
						"bank_lat": $('input[name=bank_lat]').val(),
						"bank_long": $('input[name=bank_long]').val()
					};
					$.ajax({
						type : 'POST',
						url	: "<?php echo $baseUrl; ?>/api/saveBank",
						data : formData,
						encode : true
					}).done(function(data) {
						$('.alert').empty();
						var message = "";
						var type = "";
						if(data["message"] == "success") {
							type = "Success";
							message = "Bank Information save success.";
							$('.alert').removeClass('alert-danger').addClass('alert-success');
							window.setTimeout(function(){
								$('#backFrm').attr('action', "<?= $baseUrl ?>/branch-input").submit();
							}, 2 * 1000);
						} else {
							type = "Error";
							message = "Bank Infomration save error.";
							$('.alert').removeClass('alert-success').addClass('alert-danger');
						}
						$('.alert').append(`<strong>${type}!</strong> ${message}<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>`);
						$('.alert').show();
						$(window).scrollTop(0);
						console.log(data); 
					});
					event.preventDefault();
				})

				function townshipDataChange(cityId) {
					$.get("<?php echo $baseUrl; ?>/api/v2/township?filter=cityid,eq," + cityId, function(data) {
						$('#townshipDropDown').empty();
						var townshipList = data.township;
						for(var index in townshipList) {
							if(townshipList[index].id == <?= $townshipId ?>) {
								$('#townshipDropDown').append("<option value='" + townshipList[index].id + "' selected>" + townshipList[index].township + "</option>");
							} else {
								$('#townshipDropDown').append("<option value='" + townshipList[index].id + "'>" + townshipList[index].township + "</option>");
							}
						}
						$('#townshipDropDown').selectpicker('refresh');
					})
				}

				function setBankType() {
					$('#bank_type').empty();
					$('#bank_type').append('<option value="none" disabled>အမျိုးအစားရွေးရန်</option><option value="branch">ဘဏ်ခွဲ</option><option value="atm">ATM</option>');
					$('#bank_type').selectpicker('refresh');
				}
			})
		</script>
	</body>
</html>