<!DOCTYPE html>
<html>
	<head>
		<title>Home | $ Exchange Rate</title>
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
		
		<link rel="shortcut icon" href="<?php echo $baseUrl; ?>/resources/img/mycurrency.png" type="img/png">
		<meta name='description' content='Api မှ data များသည် Website များမှ ယူထားခြင်းဖြစ်ပါသည်။ အခမဲ့အသုံးပြုလို့ရအောင်လုပ်ပေးထားခြင်းဖြစ်ပါသည်။'>
		<meta name='title' content='Home | $ Exchange Rate'>
		<meta name='og:title' content='Home | $ Exchange Rate'/>
	    <meta property='og:image' content='https://kyawhtut.com/public/img/mmexchange-screen-shoot.png' />
	    <meta property='og:description' content='Api မှ data များသည် Website များမှ ယူထားခြင်းဖြစ်ပါသည်။ အခမဲ့အသုံးပြုလို့ရအောင်လုပ်ပေးထားခြင်းဖြစ်ပါသည်။' />
	    <meta name='og:author' content='Kyaw Htut'/>
	    <meta name='og:image:alt' content='Kyaw Htut'/>
	    <meta property='og:url' content='https://kyawhtut.com/mmexchange/' />
	    <meta name='author' content='Kyaw Htut'>
	    <meta name="theme-color" content="#33475e">

		<link rel="stylesheet" href="<?= $baseUrl; ?>/resources/css/4.3.1/bootstrap.min.css">
		<link rel="stylesheet" href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css">
		<link rel="stylesheet" href="<?= $baseUrl; ?>/resources/css/style.css">
		<!-- <link rel="stylesheet" href="http://t1m0n.name/air-datepicker/dist/css/datepicker.min.css"> -->
		<link rel="stylesheet" href="<?= $baseUrl; ?>/resources/css/font-awesome.css">
		<style>
			body {
				margin: 50px 0 0;
				padding: 0;
				width: 100%;
				font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
				text-align: center;
				color: #aaa;
				font-size: 18px;
			}

			h3 {
				color: #33475e;
				letter-spacing: -3px;
				font-family: 'Lato', sans-serif;
				font-size: 42px;
				font-weight: 200;
			}

			.table>thead>tr>.currency {
				background-color: #64bd53!important;
				color: white;
			}

			.table>thead>tr>.buy {
				background-color: #0155b8!important;
				color: white;
			}

			.table>thead>tr>.sell {
				background-color: #013c4e!important;
				color: white;
			}

			.table>thead>tr>th {
				text-align: center;
				border-bottom: none;
			}

			.table-striped>tbody>tr {
				color: #333333;
				background-color: #f2f2f2!important;
			}

			.table-striped>tbody>tr:nth-of-type(odd) {
				background-color: #ffffff!important;
			}

			.card-title {
				text-align: left;
				font-size: 22px;
				font-weight: 200;
			}
		</style>
	</head>
	<body>
		<nav class="navbar navbar-expand-lg fixed-top navbar-light bg-light">
			<a class="navbar-brand" href="<?= $baseUrl; ?>">My Currency</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarTogglerDemo02">
				<div class="navbar-nav mr-auto mt-2 mt-lg-0"></div>
				<ul class="navbar-nav my-2 my-lg-0">
					<li class="nav-item text-left pr-5"><a href="convert">Exchange Converter</a></li>
					<li class="nav-item text-left"><a href="http://bit.ly/kh-mycurrency">Apk Download</a></li>
				</ul>
			</div>
		</nav>
		<div class="container" style="margin-top: 72px;">
			<div class="row mb-3">
				<div class="col-sm-8">
					<h3 class="text-left">Today Exchange</h3>
				</div>
				<div class="col-sm-4 m-auto">
					<input id="datepicker" name="date" />
				</div>
			</div>
			<div class="clearfix"></div>
			<div class="card-columns">
				<?= $exchangeView; ?>
			</div>	
			<p style="color: #a97c14;">
				Data များသည် သက်ဆိုင်ရာ ဘဏ်များ ၏ Website များမှ ယူထားခြင်းဖြစ်ပြီး အခမဲ့အသုံးပြုလို့ရအောင်လုပ်ပေးထားခြင်းဖြစ်ပါသည်။
			</p>
    		<p>Developed by Kyaw Htut <a href="mailto:developer.kyawhtut@gmail.com" style="color: #719e40;">developer.kyawhtut@gmail.com</a></p>
			<p style="text-align: right;"><a href="api" style="color: #719e40">Api For Developer</a></p>
		</div>

		<form action="<?= $baseUrl; ?>/" method="get" id="backFrm"></form>
		<script src="<?= $baseUrl; ?>/resources/js/jquery.js"></script>
		<script src="<?= $baseUrl; ?>/resources/js/4.3.1/bootstrap.min.js"></script>
		<script src="<?= $baseUrl; ?>/resources/js/popper.min.js"></script>
		<script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js"></script>
		<script type="text/javascript">
			$(document).ready(function() {
				var date = new Date();
				var selectedDate = `<?= $selectedDate; ?>`;
				var today = date.getFullYear() + '-' + ('0'+(date.getMonth()+1)).slice(-2) + '-' + ('0'+date.getDate()).slice(-2);
				if(selectedDate == "") {
					selectedDate = today;
				}

				$('#datepicker').datepicker({
					footer: true, 
					modal: false, 
					header: false,
					size: 'large',
					showOtherMonths: true,
					format: 'yyyy-mm-dd',
					value:  selectedDate,
					minDate: "2019-07-08",
					maxDate: today,
					change: function(e) {
						$('#backFrm').attr('action', "<?= $baseUrl ?>/" + $('#datepicker').val()).submit();
					}
				});

				$('.gj-datepicker').addClass('float-right');
			});
		</script>
	</body>
</html>