<!DOCTYPE html>
<html>
	<head>
		<title>Page Not Found | $ Exchange Rate</title>
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
		
		<link rel="shortcut icon" href="resources/img/profile.jpg" type="img/png">
		<meta name='description' content='Api မှ data များသည် Website များမှ ယူထားခြင်းဖြစ်ပါသည်။ အခမဲ့အသုံးပြုလို့ရအောင်လုပ်ပေးထားခြင်းဖြစ်ပါသည်။'>
		<meta name='title' content='Home | $ Exchange Rate'>
		<meta name='og:title' content='Page Not Found | $ Exchange Rate'/>
	    <meta property='og:image' content='resources/img/profile.jpg' />
	    <meta property='og:description' content='Api မှ data များသည် Website များမှ ယူထားခြင်းဖြစ်ပါသည်။ အခမဲ့အသုံးပြုလို့ရအောင်လုပ်ပေးထားခြင်းဖြစ်ပါသည်။' />
	    <meta name='og:author' content='Kyaw Htut'/>
	    <meta name='og:image:alt' content='Kyaw Htut'/>
	    <meta property='og:url' content='https://kyawhtut.com/mmexchange/' />
	    <meta name='author' content='Kyaw Htut'>
	    <meta name="theme-color" content="#719e40">

		<style>
			body {
				margin: 50px 0 0;
				padding: 0;
				width: 100%;
				font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
				text-align: center;
				color: #aaa;
				font-size: 18px;
			}

			h3 {
				color: #c53131;
				letter-spacing: -3px;
				font-family: 'Lato', sans-serif;
				font-size: 50px;
				font-weight: 200;
				margin-bottom: 0;
			}
		</style>
	</head>
	<body>
		<h3>Page Not Found</h3>
		<h5>The equest page "<?= htmlspecialchars($path); ?>" could not be found.</h5>
	</body>
</html>