<!DOCTYPE html>
<html>
	<head>
		<title>Today Exchange Rate </title>
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
		<link rel="shortcut icon" href="http://localhost:8000/resources/img/ucstgo-logo.png" type="image/png">
		<style>
			body {
				margin: 50px 0 0;
				padding: 0;
				width: 100%;
				font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
				text-align: center;
				color: #aaa;
				font-size: 18px;
			}

			h3 {
				color: #719e40;
				letter-spacing: -3px;
				font-family: 'Lato', sans-serif;
				font-size: 50px;
				font-weight: 200;
				margin-bottom: 0;
			}
		</style>
	</head>
	<body>
		<h3>$ Exchange Rate</h3>
		<h5>Exchange rate successful for today.</h5>
	</body>
</html>